name:  challed_ch2

on: [push]

jobs:
  job1:
    name: printing date on ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: checkout first
      uses: actions/checkout@v1
    - name: print date
      run: date "+%H:%M:%S   %d/%m/%y"

  job2:
    name: printing date on windows
    runs-on: windows-latest
    steps:
    - name: checkout first
      uses: actions/checkout@v1
    - name: print date
      run: "Get-Date"
